language: node_js
node_js:
  - '10.15.3'

cache:
  directories:
    - ./node_modules

install:
  - npm install

script: node_modules/karma/bin/karma start karma.conf.js --single-run
before_script:
    - npm install