language: node_js
node_js:
  - '10.15.3'
addons:
chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm test
  # - npm run lint:report

before_script:
  - npm install